### ISSUE TITLE
Support for mobile

### ISSUE THREAD

**Issue by xpluscal** [elmarti/meteor-video-chat#1]
Hi,
is there going to be support for device video access via Cordova?

**Comment by elmarti** [comment]
Hi, I'll have a look into this tomorrow and give you a timeframe. I've developed a video chat app with just Cordova, but not Meteor so I'm not 100% sure right now.

**Comment by xpluscal** [comment]
Nice, did you build the cordova app with webrtc as well?
Is there a repository for the app?

**Comment by elmarti** [comment]
Unfortunately it's not open source, but I used this extension https://github.com/alongubkin/phonertc

**Comment by xpluscal** [comment]
I see. It seems that it's not too easy to integrate with meteor.
Did you get phonertc working on iOS as well?

Thanks for your quick replies.

**Comment by elmarti** [comment]
That's alright! I didn't, I kept having interoperability issues so only built it or Android.

**Comment by elmarti** [comment]
I'll have a look into it over the next month, I'm pretty busy for the next 2 weeks but I'm more than happy to to give it a go.

**Comment by elmarti** [comment]
Hi there, I know it's been a while, but I'm looking into moving a native app into Meteor/Cordova so I'll have a looksee and close this if I'm successful

**Comment by elmarti** [comment]
A version supporting Cordova Android and iPhone will be pushed up within the week
