### ISSUE TITLE
ICE Failed - ice state change failed

### ISSUE THREAD

**Issue by gbonnard** [elmarti/meteor-video-chat#14]
Hi elmarti,

Thanks for the good work done packaging webrtc for meteor, the basic are very useful.
I'm testing a basic video chat app and I'm having an ICE Failed error.
Attached you will find my code : a basic html template - and the js that i'm using.
If you had any idea of what the issue might be it would be of great help.
Many Thanks,
Gaël

[videoApp.txt](https://github.com/elmarti/meteor-video-chat/files/445007/videoApp.txt)

**Comment by elmarti** [comment]
Hi Gaël, I'm just working on something I'll have a look later tonight and get it working. In the next few days I will be publishing a complete re-write of this so  you may want to wait or use a static version once I get the fix up

**Comment by gbonnard** [comment]
Thanks, I've noticed that the example works with the 0.4.7 version of the package but not with 0.4.12. I'll use that one in the meantime.

Cheers,

Gaël

**Comment by elmarti** [comment]
I've only posted patches since creating the example so i'll roll the version back before publishing the re-write
