### ISSUE TITLE
awesome! any ETA on decoupling for react users?

### ISSUE THREAD

**Issue by acomito** [elmarti/meteor-video-chat#16]
Or would this work with something like blaze-in-react?

**Comment by elmarti** [comment]
Hi @acomito, earliest start of next week. To be fair you could use the below design pattern, but the new extension will work completely differently to the current one. 

```
import React from 'react';
import Blaze from 'meteor/gadicc:blaze-react-component';

const App = () => (
  <div>
    <Blaze template="renderCallTemplate" />
  </div>
);
```

**Comment by elmarti** [comment]
Finally had a bit more time to work on this, master currently has a version where Blaze is not required. I'm currently working on a big refactor, decoupling from MongoDB for DDP, which will most likely give birth to another package!
