### ISSUE TITLE
Firefox 47 Possible bug?

### ISSUE THREAD

**Issue by flaviocarvalho** [elmarti/meteor-video-chat#3]
Hey, so my stream is showing in chrome, but it doesn't work in the latest version of Firefox..
all i'm doing is:
`Meteor.VideoCallServices.setLocalWebcam( 'myCamera' );
Meteor.VideoCallServices.loadLocalWebcam( true );`

Other than that, I love this package! ;)

**Comment by elmarti** [comment]
Hi Flavio, thanks a lot! I did actually pick up an error in the _loadWebcam function which I am about to fix, is there anything printed to the console? Thanks

**Comment by elmarti** [comment]
Yes, I added in a shim for this https://developer.mozilla.org/en/docs/Web/API/Navigator/getUserMedia but it broke for other browsers so I commented it out and forgot! It should be working now, I'll have a bit more time to work on it tomorrow and I'll most likely replace my shim code with this https://github.com/addyosmani/getUserMedia.js/

**Comment by flaviocarvalho** [comment]
It works, thanks!
Yea that would be awesome man!

**Comment by elmarti** [comment]
OK, I've edited and tested it now and it appears to work across the board, cheers!
