### ISSUE TITLE
onReceivePhoneCall not userId

### ISSUE THREAD

**Issue by aboire** [elmarti/meteor-video-chat#39]
The function this.onReceivePhoneCall (msg.id); Do not return the userId but the msg.id
https://github.com/elmarti/meteor-video-chat/blob/master/services/client.js#L48

**Comment by elmarti** [comment]
Nice spot, I'll have a look at this today. 

SOLUTION: 
Update the following callback: 
` this.onReceivePhoneCall(msg.id);`

to be 

` this.onReceivePhoneCall(msg.fields.caller);`

This will also be task is also an opportunity to review all of the callbacks and ensure that they are being ultilised correctly.

**Comment by aboire** [comment]
Yes I used callLog
https://github.com/elmarti/meteor-video-chat/blob/master/services/client.js#L21

**Comment by aboire** [comment]
For the browser and desktop (electron) is ok, I will test with cordova (crosswalk) I think I need to add permissions

**Comment by aboire** [comment]
Ok it works without permission in addition with crosswalk :)

**Comment by elmarti** [comment]
Great, thanks a lot for that, I wasn't going to get time to check any time soon

**Comment by elmarti** [comment]
All fixed and tested, thanks for the heads up https://github.com/elmarti/meteor-video-chat/releases/tag/1.0.10
