### ISSUE TITLE
broadcasting ...

### ISSUE THREAD

**Issue by tomvolek** [elmarti/meteor-video-chat#57]
Elmarti :  Is brodcasting anywhere in your future plans ?  Even though you are doing person to person   video in this package , I need to broadcast audio only.  Any suggestion ? ie an admin broadcast his microphone to all connected clients . 

Thanks
Tom

**Comment by elmarti** [comment]
Hi, WebRTC only really supports peer-to-peer communication, there would be a way to do it with a peer-to-peer network like Peer5 https://www.peer5.com, or an audio streaming server would be more stable. Unfortunately this is well outside the scope of this project, I do plan to look into more complex network topologies but this will be a long way down the line.

**Comment by elmarti** [comment]
ALTHOUGH, if you were to broadcast to only a limited number of users, you could implement a basic network topology using raw WebRTC.
