### ISSUE TITLE
Exception in queued tasks

### ISSUE THREAD

**Issue by flaviocarvalho** [elmarti/meteor-video-chat#6]
Ok, everything works now, I wasn't loading my template the right way.. lol
I'm getting this Exception console.log on server restart:

> I20160710-12:01:31.405(-5)? Exception in queued task: Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
> I20160710-12:01:31.406(-5)?     at AccountsServer.userId (packages/accounts-base/accounts_server.js:82:13)
> I20160710-12:01:31.406(-5)?     at Object.Meteor.userId (packages/accounts-base/accounts_common.js:237:19)
> I20160710-12:01:31.406(-5)?     at Object.removed (packages/elmarti:video-chat-custom/services/server.js:51:39)
> I20160710-12:01:31.406(-5)?     at [object Object].observeChangesCallbacks.removed (packages/minimongo/observe.js:169:1)
> I20160710-12:01:31.407(-5)?     at self.applyChange.removed (packages/minimongo/observe.js:71:1)
> I20160710-12:01:31.407(-5)?     at packages/mongo/observe_multiplex.js:183:30
> I20160710-12:01:31.409(-5)?     at Function._.each._.forEach (packages/underscore/underscore.js:108:1)
> I20160710-12:01:31.410(-5)?     at Object.task (packages/mongo/observe_multiplex.js:177:9)
> I20160710-12:01:31.410(-5)?     at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
> I20160710-12:01:31.412(-5)?     at packages/meteor/fiber_helpers.js:125:1

Still works, but im not sure if I should be worried about that..
Also I get `onaddstream is deprecated! Use peerConnection.ontrack instead.` on firefox console

**Comment by elmarti** [comment]
I've literally just picked this up as well

**Comment by elmarti** [comment]
Publishing the fix now

**Comment by elmarti** [comment]
with regards to the onaddstream, it's not breaking anything at the moment, but I am actively looking for a shim to make WebRTC play better
