### ISSUE TITLE
on**** function in lib/client.js

### ISSUE THREAD

**Issue by wei170** [elmarti/meteor-video-chat#77]
`onTargetAccept()` and other functions in the `client.js` do nothing. But in the blaze example and react example codes, they all are used.

**Comment by wei170** [comment]
Sorry, I ask it in the wrong way. I would like those functions to change my local `state`. Seems that they were not be triggered. Do you know how to do that?

Thank you.

**Comment by elmarti** [comment]
I can see a bug with `onTargetAccept` alone, are there any others with issues?

**Comment by elmarti** [comment]
Good find, it's due to the original Meteor Video Chat code being replaced with RTCFly as the core. A patch has been pushed to 2.1.5
