### ISSUE TITLE
Mute functioning?

### ISSUE THREAD

**Issue by awgust-taylor** [elmarti/meteor-video-chat#79]
Is there any way to implement mute()? I have been searching for all kind of info but there is none and the source code isn't very clear imo. I would give this package 2 thumbs up if I can manipulate the mute and camera facing features however getting to the userMedia seems to be a mission. Can anyone else provide any instructions? SimpleWebRTC not so simple it seems.

**Comment by elmarti** [comment]
Hi, yes you are right, it relies on another project I am working on https://github.com/RTCFly/RTCFly. 
At the moment you can use `VideoCallServices.core.getLocalVideo()`, which will return an instance of `VideoWrapper`. https://github.com/RTCFly/RTCFly/blob/master/VideoWrapper.ts On there you can call `getElement` and then set the `muted` attribute to true, so like this: 

```
const localVideo = VideoCallServices.core.getLocalVideo();
// or getRemoteVide()
if(localVideo !== undefined){
   localVideo.getElement().muted = true; 
}
```

I'm aware that this is not ideal, I can add these methods to the `VideoCallServices` object for ease of access?

**Comment by awgust-taylor** [comment]
hi elmarti thank you so much for the quick reply. If you can add those methods that would be awesome, not just for me but for the package and the community in a whole. You are a rockstar mate thanks again. Hopefully one day we coders cross paths so I can buy you a coffee or something, I definitely don't forget good people.

**Comment by elmarti** [comment]
Thank you! I've done some work on this branch https://github.com/elmarti/meteor-video-chat/tree/79-add-local-and-remote-video-getters adding 
```
getLocalVideo
getRemoteVideo
toggleLocalMute
toggleRemoteMute
```
I still have some testing to do but that should be done today or tomorrow

**Comment by awgust-taylor** [comment]
hey elmarti you helped so much in the last post i had to star you haha, I just wanted to ask you in regards to your package one more thing. Can i use the getLocalVideo to switch between front and rear camera devices? Prior to your update the `getElement().muted = true` worked. Does the object thats returned in the getElement  function have device choice / camera facing properties?

**Comment by elmarti** [comment]
As far as I know, you they are treated as separate streams, so changing the streams will require renegotiation, which isn't currently handled by this package, but it's in the pipeline for the rebuild of the core package https://github.com/RTCFly/RTCFly/issues/19. So hopefully in the next few months that will be possible. I'll create a new issue so it's know that it's needed and will be integrated as soon as it's built

**Comment by elmarti** [comment]
2.2.1 Released: https://github.com/elmarti/meteor-video-chat/releases/tag/2.2.1
Atmosphere: https://atmospherejs.com/elmarti/video-chat
Example App (With new mute functionality) https://blazevideochat.herokuapp.com/
Example App code https://github.com/elmarti/blaze-video-chat
