### ISSUE TITLE
Improved cross-browser compatibility

### ISSUE THREAD

**Issue by elmarti** [elmarti/meteor-video-chat#9]
At present, the system relies on basic polyfills to support a wider array of browsers, however it has been decided that a dedicated package should be used to ensure functionality across all compatible browsers.

**Comment by elmarti** [comment]
Simplistic polyfill and support detection https://www.npmjs.com/package/getusermedia

**Comment by elmarti** [comment]
More functionality, maybe too much for this project https://www.npmjs.com/package/getusermedia-js

**Comment by flaviocarvalho** [comment]
I'll probably help out soon with whatever is needed

**Comment by elmarti** [comment]
Thanks, I've added https://www.npmjs.com/package/getusermedia and it works a charm! I'm just keeping this open in case any can suggest something else to improve browser support.
